; Override PHP — E-Dokter RSUD
memory_limit=256M
max_execution_time=120
max_input_vars=5000

; Upload berkas rawat (PDF/scan)
upload_max_filesize=25M
post_max_size=30M

expose_php=0
date.timezone=Asia/Makassar
